version: '2'

services:
  teduexam:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  teduexam.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
